# Generated by Django 4.2.7 on 2024-01-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedIn',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(default='computer sicence', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='x_link',
            field=models.URLField(default='https://jaksjak.com'),
            preserve_default=False,
        ),
    ]
