# Generated by Django 4.2.7 on 2024-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_fist_name_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(default='betweenl lfiew'),
            preserve_default=False,
        ),
    ]
