# Generated by Django 4.2.7 on 2024-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_studentprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
