# Generated by Django 4.2.7 on 2024-01-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='adjkas.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
